version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${COOG_MAIN_DATABASE:?}
      - ON_ERROR_STOP=0
    volumes:
      - ${POSTGRES_DATA_VOLUME:?}:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
