services:
  postgres:
    image: postgres:12-alpine
    command: -c max_locks_per_transaction=1024
    env_file:
      - env/postgres.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - ON_ERROR_STOP=0
    volumes:
      - ${POSTGRES_DATA_VOLUME:?}:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
