version: '3'
networks:
  backend:

services:

  celery_daily:
    image: coopengo/coog:${IMAGE_VERSION_COOG}
    command: ["daily", "4", "french_work_days"]
    env_file:
      - env_files/var.env
      - env_files/celery.env
    volumes:
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    networks:
      - backend
