version: '3'
networks:
  backend:

services:

  celery:
    image: coopengo/coog:${IMAGE_VERSION_COOG}
    command: ["celery", "${NUM_WORKERS}"]
    container_name: celery-${BATCH_NAME}
    env_file:
      - env_files/var.env
      - env_files/celery.env
    volumes:
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    deploy:
      resources:
        limits:
          memory: 16G
    networks:
      - backend
