version: '3.5'

#services:
#  coog:
#    image: coopengohub/coog-:${IMAGE_VERSION_COOG}
#  initcoog:
#    image: coopengohub/coog-:${IMAGE_VERSION_COOG}
#  celery:
#    image: coopengohub/coog-:${IMAGE_VERSION_COOG}
#  celery_single:
#    image: coopengohub/coog-:${IMAGE_VERSION_COOG}

