version: "3.9"

#services:
#  coog:
#    image: ${IMAGE_REGISTRY}/coog-:${IMAGE_VERSION_COOG}
#  initcoog:
#    image: ${IMAGE_REGISTRY}/coog-:${IMAGE_VERSION_COOG}
#  celery:
#    image: ${IMAGE_REGISTRY}/coog-:${IMAGE_VERSION_COOG}
#  celery_single:
#    image: ${IMAGE_REGISTRY}/coog-:${IMAGE_VERSION_COOG}

