version: '3'

services:
  reverse-proxy:
    image: traefik:2.2.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  coog:
    image: coopengo/coog:coog-2.7.21
    command: ["server", "1"]
    depends_on:
      - redis
      - postgres
    env_file:
      - var.env
    labels:
      -  "traefik.http.routers.coog.rule=Host(`coog.localhost`)"

  postgres:
    image: postgres:12-alpine
    env_file:
      - postgres.env
    volumes:
      #- ./init-user-db.sh:/docker-entrypoint-initdb.d/1_init-user-db.sh
      - ./coog27.sql:/docker-entrypoint-initdb.d/2_coog27.sql:ro

  redis:
    image: redis:5.0.7-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    image: mongo
    env_file:
      - var.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
     # - ./mongo-volume:/data/db
 
  gateway:
    image: coopengo/gateway:coog-2.7.21
    env_file:
      - var.env
    depends_on:
      - mongo
    labels:
      - "traefik.http.routers.gateway.middlewares=gateway"
      - "traefik.http.routers.gateway.rule=Host(`coog.localhost`) && PathPrefix(`/gateway`)"
      - "traefik.http.middlewares.gateway.replacepathregex.regex=/gateway(/|$$)(.*)"
      - "traefik.http.middlewares.gateway.replacepathregex.replacement=/$${2}"

  api:
    image: coopengo/api:coog-2.7.21
    env_file:
      - var.env
    depends_on:
      - mongo

  api-b2b-config:
    image: coopengo/api-b2b-config:coog-2.7.21
    env_file:
      - var.env
    depends_on:
      - mongo

  api-referential:
    image: coopengo/api-referential:coog-2.7.21
    env_file:
      - var.env
    depends_on:
      - mongo

  api-identity-manager:
    image: coopengo/api-identity-manager:coog-2.7.21
    env_file:
      - var.env
    depends_on:
      - mongo
      - api

  web:
    image: coopengo/web:coog-2.7.21
    env_file:
      - var.env
    command: ["server", "1"]
    depends_on:
      - redis

  portal:
    image: coopengo/portal:coog-2.7.21
    command: ["server", "1"]
    env_file:
      - var.env
    labels:
      - "traefik.http.routers.portal.middlewares=portal"
      - "traefik.http.routers.portal.rule=Host(`coog.localhost`) && PathPrefix(`/portal`)"
      - "traefik.http.middlewares.portal.replacepathregex.regex=/portal(/|$$)(.*)"
      - "traefik.http.middlewares.portal.replacepathregex.replacement=/$${2}"

  static:
    image: coopengo/static:master
    labels:
      - "traefik.http.routers.static.rule=Host(`coog.localhost`) && ( PathPrefix(`/sao`) || PathPrefix(`/doc`) || PathPrefix(`/bench`) )"

  busybox:
    image: busybox
    command: tail -f /dev/null

  centos:
    image: centos
    command: tail -f /dev/null

