version: "3.9"

services:
  app-b2c:
    image: ${IMAGE_REGISTRY}/app-b2c:${IMAGE_VERSION_APP_B2C}
    environment:
      - COOG_URL=$COOG_INTERNAL_URL
      - COOG_DB_NAME=$COOG_MAIN_DATABASE
      - JWT_INTERNAL_ENCRYPTION=$JWT_INTERNAL_ENCRYPTION
    depends_on:
      - mongo
      - api
    networks:
      - backend
