version: "3.9"

networks:
  frontend:
    driver: bridge
    name: ${NETWORK_FRONTEND_NAME}
    ipam:
      config:
      - subnet:  ${NETWORK_FRONTEND_SUBNET}
  backend:
    name: ${NETWORK_BACKEND_NAME}
    ipam:
      config:
      - subnet:  ${NETWORK_BACKEND_SUBNET}

services:
  reverse-proxy:
    image: traefik:2.3.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../certs:/etc/certs:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../traefik/traefik.config.toml:/etc/traefik/traefik.config.toml:ro
      - ../traefik/acme.json:/acme.json:rw
    networks:
      - backend
      - frontend
    profiles:
      - base
      - backend
      - frontend
