version: "3.9"

services:
  coog:
    image: ${IMAGE_REGISTRY}/coog:${IMAGE_VERSION_COOG}
    command: ["server", "1"]
    env_file:
      - env/var.env
    depends_on:
      - init
    labels:
      - traefik.enable=true
      - traefik.http.routers.coog.rule=Host(`${COOG_HOSTNAME}`)
      - traefik.http.routers.coog.entrypoints=http
      - traefik.http.routers.coog_s.rule=Host(`${COOG_HOSTNAME}`)
      - traefik.http.routers.coog_s.entrypoints=https
      - traefik.http.routers.coog_s.tls=true
    restart: always
    volumes:
      - ${COOG_TMP}:/workspace/tmp
      - ${COOG_VOLUME}:/workspace/io
      - ./conf/coog.conf:/workspace/coog.conf:ro
      - ./conf/batch.conf:/workspace/batch.conf:ro
    networks:
      - backend
