version: "3.9"

services:
  gateway:
    image: ${IMAGE_REGISTRY}/gateway:${IMAGE_VERSION_GATEWAY}
    env_file:
      - env/var.env
    depends_on:
      - mongo
    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway.rule=Host(`${PROJECT_HOSTNAME}`) && PathPrefix(`/gateway`)
      - traefik.http.routers.gateway.entrypoints=http
      - traefik.http.routers.gateway.middlewares=gateway
      - traefik.http.middlewares.gateway.replacepathregex.regex=/gateway(/|$$)(.*)
      - traefik.http.middlewares.gateway.replacepathregex.replacement=/$${2}
      - traefik.http.routers.gateway_s.rule=Host(`${PROJECT_HOSTNAME}`) && PathPrefix(`/gateway`)
      - traefik.http.routers.gateway_s.middlewares=gateway_s
      - traefik.http.middlewares.gateway_s.replacepathregex.regex=/gateway(/|$$)(.*)
      - traefik.http.middlewares.gateway_s.replacepathregex.replacement=/$${2}
      - traefik.http.routers.gateway_s.entrypoints=https
      - traefik.http.routers.gateway_s.tls=true
    restart: always
    networks:
      - backend
      - frontend
