version: "3.9"

services:
  api:
    image: ${IMAGE_REGISTRY}/api:${IMAGE_VERSION_API}
    env_file:
      - env/var.env
    depends_on:
      - mongo
    restart: always
    networks:
      - backend
    profiles:
      - frontend
